import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { GraphQLClient, gql } from 'graphql-request';
import Random from './random';
import BlogCard from '../components/BlogCard';

const graphcms = new GraphQLClient(
  "https://api-ap-south-1.hygraph.com/v2/clfh7d7rx0awl01ue235sa78t/master"
);

const QUERY = gql`
{
  posts{
    id,
    title,
    datePublished,
    slug,
    content {
      html
    }
    author{
      name,
      avatar{
        url
      }
    },
    coverPhoto{
      id,
      url
    }
  }
}
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {

  return (

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          Hii there
          {/* {posts.map((p) => {console.log(p.coverPhoto.url)})} */}
          {
            posts.map((post) => (
              <BlogCard 
                title={post.title}
                author={post.author}
                coverPhoto={post.coverPhoto}
                key={post.id}
                datePublished={post.datePublished}
                slug={post.slug}
              />
            ))
          }
          <Random />
        </main>
      </div>

  );
}
